---

- name: create the expvip group
  group:
    name: expvip
    state: present
    gid: 1001

- name: add expvip user
  user:
    name: expvip
    group: expvip
    uid: 1001

- name: clone the expvip git repo
  git:
    repo: https://github.com/Uauy-Lab/expvip-web.git
    dest: "{{ app_dir }}" 
  become: yes
  become_user: expvip
  ignore_errors: yes

- name: run npm install  
  command: npm install
  args:
    creates: "{{ app_dir }}/node_modules/bio-vis-expression-bar/index.js"
    chdir: "{{ app_dir }}"
  become: yes
  become_user: expvip

- name: run bundle install
  shell: |
    scl enable rh-ruby23 -- bundle install
  args:
    creates: "{{ app_dir}}/.gem/ruby/bin/sequenceserver"
    chdir: "{{ app_dir }}"
  become: yes
  become_user: expvip

- name: copy over activate.sh script
  copy:
    src: activate.sh
    dest: /home/expvip/activate.sh
  become: yes
  become_user: expvip

- name: copy over sequenceserver conf file
  copy:
    src: sequenceserver.conf
    dest: /home/expvip/.sequenceserver.conf
  become: yes
  become_user: expvip
