---

- name: start and enable the mysql server
  service:
    name: mariadb
    state: started
    enabled: yes

- name: update the mysql root password for all accounts
  mysql_user:
    name: root
    host: [ "{{ ansible_hostname }}", "127.0.0.1", "::1"]
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

# Force localhost to be last for idempotency.
- name: update the mysql root password for all accounts
  mysql_user:
    name: root
    host: "localhost"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

- name: copy .my.cnf file with root password credentials
  template:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: create expvip database
  mysql_db:
    name: "{{ mysql_expvip_database }}"
    state: present

- name: create mysql expvip user
  mysql_user:
    name: "{{ mysql_expvip_user }}"
    host: "localhost"
    password: "{{ mysql_expvip_user_password }}"
    priv: "{{ mysql_expvip_database }}.*:ALL,GRANT"
