---

- name: start and enable the mysql server
  service:
    name: mariadb
    state: started
    enabled: yes

- name: update the mysql root password for all accounts
  mysql_user:
    name: root
    host: [ "{{ ansible_hostname }}", "127.0.0.1", "::1"]
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

# Force localhost to be last for idempotency.
- name: update the mysql root password for all accounts
  mysql_user:
    name: root
    host: "localhost"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

- name: copy .my.cnf file with root password credentials
  template:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: create expvip database
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mysql_db_prefix}}{{ mysql_dev_db_name }}"
    - "{{ mysql_db_prefix}}{{ mysql_test_db_name }}"
    - "{{ mysql_db_prefix}}{{ mysql_prod_db_name }}"

- name: give mysql db user access to expvip dbs
  mysql_user:
    name: "{{ mysql_db_user }}"
    host: "localhost"
    password: "{{ mysql_db_user_password }}"
    priv: "{{ mysql_db_prefix }}%.*:ALL,GRANT"

- name: update the config/database.yml file
  template:
    src: webapp_config.yml
    dest: "/home/expvip/expvip_web/config/database.yml"
